import type { Values } from "./values";

export const CAR_SETUP_CHANGE_TYPES = {
  CHASSIS: "CHASSIS",

  FRONT_CAMBER: "FRONT_CAMBER",
  REAR_CAMBER: "REAR_CAMBER",
  FRONT_CASTER: "FRONT_CASTER",
  REAR_CASTER: "REAR_CASTER",
  DIFF_TYPE: "DIFF_TYPE",
  DIFF_OIL: "DIFF_OIL",
  FRONT_TOE: "FRONT_TOE",
  REAR_TOE: "REAR_TOE",
  ACKERMAN: "ACKERMAN",
  SPRING_STIFFNESS_FRONT: "SPRING_STIFFNESS_FRONT",
  SPRING_STIFFNESS_REAR: "SPRING_STIFFNESS_REAR",
  OIL_THICKNESS_FRONT: "OIL_THICKNESS_FRONT",
  OIL_THICKNESS_REAR: "OIL_THICKNESS_REAR",
  REAR_SHOCK_ANGLE: "REAR_SHOCK_ANGLE",
  FRONT_SHOCK_ANGLE: "FRONT_SHOCK_ANGLE",
  REAR_SHOCK_REBOUND: "REAR_SHOCK_REBOUND",
  FRONT_SHOCK_REBOUND: "FRONT_SHOCK_REBOUND",

  RIDE_HEIGHT_FRONT: "RIDE_HEIGHT_FRONT",
  RIDE_HEIGHT_REAR: "RIDE_HEIGHT_REAR",
  DROOP_FRONT: "DROOP_FRONT",
  DROOP_REAR: "DROOP_REAR",
  SHOCK_MOUNT_FRONT: "SHOCK_MOUNT_FRONT",
  SHOCK_MOUNT_REAR: "SHOCK_MOUNT_REAR",
  UPPER_ARM_LENGTH: "UPPER_ARM_LENGTH",
  LOWER_ARM_LENGTH_FRONT: "LOWER_ARM_LENGTH_FRONT",
  LOWER_ARM_LENGTH_REAR: "LOWER_ARM_LENGTH_REAR",
  KPI_ANGLE: "KPI_ANGLE",

  GYRO_GAIN: "GYRO_GAIN",
  GYRO_ORIENTATION: "GYRO_ORIENTATION",
  SERVO_SPEED: "SERVO_SPEED",
  SERVO_TORQUE: "SERVO_TORQUE",
  SERVO_HORN_LENGTH: "SERVO_HORN_LENGTH",
  BUMP_STEER_SETTING: "BUMP_STEER_SETTING",
  STEERING_RATE: "STEERING_RATE",

  MOTOR_POSITION: "MOTOR_POSITION",
  SPUR_GEAR: "SPUR_GEAR",
  PINION_GEAR: "PINION_GEAR",
  FDR: "FDR",
  BELT_TENSION: "BELT_TENSION",

  FRONT_WHEEL_OFFSET: "FRONT_WHEEL_OFFSET",
  REAR_WHEEL_OFFSET: "REAR_WHEEL_OFFSET",

  ESC_BOOST: "ESC_BOOST",
  ESC_TURBO: "ESC_TURBO",
  BATTERY_TYPE: "BATTERY_TYPE",
} as const;

export type CarSetupChangeTypes = Values<typeof CAR_SETUP_CHANGE_TYPES>;

const CAR_SETUP_CHANGE_VALUES = {
  [CAR_SETUP_CHANGE_TYPES.CHASSIS]: {
    rdx: "Rêve'd RDX",
    rd2: "Yokomo RD2.0",
    rd1: "Yokomo RD1.0",
    sd1: "Yokomo SD1.0",
    sd2: "Yokomo SD2.0",
    sd3: "Yokomo SD3.0",
    md1: "Yokomo MD1.0",
    md2: "Yokomo MD2.0",
    md3: "Yokomo MD3.0",
    yd2: "Yokomo YD-2",
    galm: "Overdose GALM",
    rmx2: "MST RMX 2.0",
    rmx25: "MST RMX 2.5",
    fmx2: "MST FMX 2.0",
    fxx2: "MST FXX 2.0",
    dc10: "Team Associated DC10",
    shark: "Rhino Racing Shark",
    other: "Other",
  },
  [CAR_SETUP_CHANGE_TYPES.FRONT_CAMBER]: {
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
    "6": "6°",
    "7": "7°",
    "8": "8°",
    "9": "9°",
    "10": "10°",
    "11": "11°",
    "12": "12°",
  },
  [CAR_SETUP_CHANGE_TYPES.REAR_CAMBER]: {
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
    "6": "6°",
    "7": "7°",
    "8": "8°",
    "9": "9°",
    "10": "10°",
    "11": "11°",
    "12": "12°",
  },
  [CAR_SETUP_CHANGE_TYPES.FRONT_CASTER]: {
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
    "6": "6°",
    "7": "7°",
    "8": "8°",
    "9": "9°",
    "10": "10°",
    "11": "11°",
    "12": "12°",
  },
  [CAR_SETUP_CHANGE_TYPES.REAR_CASTER]: {
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
    "6": "6°",
    "7": "7°",
    "8": "8°",
    "9": "9°",
    "10": "10°",
    "11": "11°",
    "12": "12°",
  },
  [CAR_SETUP_CHANGE_TYPES.DIFF_TYPE]: {
    open: "Open",
    geared: "Geared",
    ball: "Ball",
    spool: "Spool",
    clsd: "C-LSD",
  },
  [CAR_SETUP_CHANGE_TYPES.DIFF_OIL]: {
    thick: "Thick",
    medium: "Medium",
    thin: "Thin",
  },
  [CAR_SETUP_CHANGE_TYPES.FRONT_TOE]: {
    "-5": "-5°",
    "-4": "-4°",
    "-3": "-3°",
    "-2": "-2°",
    "-1": "-1°",
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
  },
  [CAR_SETUP_CHANGE_TYPES.REAR_TOE]: {
    "-5": "-5°",
    "-4": "-4°",
    "-3": "-3°",
    "-2": "-2°",
    "-1": "-1°",
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
  },
  [CAR_SETUP_CHANGE_TYPES.ACKERMAN]: {
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  [CAR_SETUP_CHANGE_TYPES.SPRING_STIFFNESS_FRONT]: {
    soft: "Soft",
    medium: "Medium",
    hard: "Hard",
  },
  [CAR_SETUP_CHANGE_TYPES.SPRING_STIFFNESS_REAR]: {
    soft: "Soft",
    medium: "Medium",
    hard: "Hard",
  },
  [CAR_SETUP_CHANGE_TYPES.OIL_THICKNESS_FRONT]: {
    thick: "Thick",
    medium: "Medium",
    thin: "Thin",
  },
  [CAR_SETUP_CHANGE_TYPES.OIL_THICKNESS_REAR]: {
    thick: "Thick",
    medium: "Medium",
    thin: "Thin",
  },
  [CAR_SETUP_CHANGE_TYPES.REAR_SHOCK_ANGLE]: {
    "0": "0°",
    "5": "5°",
    "10": "10°",
    "15": "15°",
    "20": "20°",
    "25": "25°",
    "30": "30°",
    "35": "35°",
    "40": "40°",
    "45": "45°",
  },
  [CAR_SETUP_CHANGE_TYPES.FRONT_SHOCK_ANGLE]: {
    "0": "0°",
    "5": "5°",
    "10": "10°",
    "15": "15°",
    "20": "20°",
    "25": "25°",
    "30": "30°",
    "35": "35°",
    "40": "40°",
    "45": "45°",
  },
  [CAR_SETUP_CHANGE_TYPES.REAR_SHOCK_REBOUND]: {
    none: "None",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  [CAR_SETUP_CHANGE_TYPES.FRONT_SHOCK_REBOUND]: {
    none: "None",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  [CAR_SETUP_CHANGE_TYPES.RIDE_HEIGHT_FRONT]: {
    "20": "20mm",
    "21": "21mm",
    "22": "22mm",
    "23": "23mm",
    "24": "24mm",
    "25": "25mm",
    "26": "26mm",
    "27": "27mm",
    "28": "28mm",
    "29": "29mm",
    "30": "30mm",
  },
  [CAR_SETUP_CHANGE_TYPES.RIDE_HEIGHT_REAR]: {
    "20": "20mm",
    "21": "21mm",
    "22": "22mm",
    "23": "23mm",
    "24": "24mm",
    "25": "25mm",
    "26": "26mm",
    "27": "27mm",
    "28": "28mm",
    "29": "29mm",
    "30": "30mm",
  },
  [CAR_SETUP_CHANGE_TYPES.DROOP_FRONT]: {
    "1": "1mm",
    "2": "2mm",
    "3": "3mm",
    "4": "4mm",
    "5": "5mm",
    "6": "6mm",
    "7": "7mm",
    "8": "8mm",
    "9": "9mm",
    "10": "10mm",
  },
  [CAR_SETUP_CHANGE_TYPES.DROOP_REAR]: {
    "1": "1mm",
    "2": "2mm",
    "3": "3mm",
    "4": "4mm",
    "5": "5mm",
    "6": "6mm",
    "7": "7mm",
    "8": "8mm",
    "9": "9mm",
    "10": "10mm",
  },
  [CAR_SETUP_CHANGE_TYPES.SHOCK_MOUNT_FRONT]: {
    inner: "Inner",
    middle: "Middle",
    outer: "Outer",
  },
  [CAR_SETUP_CHANGE_TYPES.SHOCK_MOUNT_REAR]: {
    inner: "Inner",
    middle: "Middle",
    outer: "Outer",
  },
  [CAR_SETUP_CHANGE_TYPES.UPPER_ARM_LENGTH]: {
    short: "Short",
    medium: "Medium",
    long: "Long",
  },
  [CAR_SETUP_CHANGE_TYPES.LOWER_ARM_LENGTH_FRONT]: {
    "30": "30mm",
    "32": "32mm",
    "34": "34mm",
    "36": "36mm",
    "38": "38mm",
    "40": "40mm",
    "42": "42mm",
    "44": "44mm",
    "46": "46mm",
    "48": "48mm",
    "50": "50mm",
  },
  [CAR_SETUP_CHANGE_TYPES.LOWER_ARM_LENGTH_REAR]: {
    "30": "30mm",
    "32": "32mm",
    "34": "34mm",
    "36": "36mm",
    "38": "38mm",
    "40": "40mm",
    "42": "42mm",
    "44": "44mm",
    "46": "46mm",
    "48": "48mm",
    "50": "50mm",
  },
  [CAR_SETUP_CHANGE_TYPES.KPI_ANGLE]: {
    "0": "0°",
    "1": "1°",
    "2": "2°",
    "3": "3°",
    "4": "4°",
    "5": "5°",
    "6": "6°",
    "7": "7°",
    "8": "8°",
    "9": "9°",
    "10": "10°",
  },
  [CAR_SETUP_CHANGE_TYPES.GYRO_GAIN]: {
    "0": "0%",
    "10": "10%",
    "20": "20%",
    "30": "30%",
    "40": "40%",
    "50": "50%",
    "60": "60%",
    "70": "70%",
    "80": "80%",
    "90": "90%",
    "100": "100%",
  },
  [CAR_SETUP_CHANGE_TYPES.GYRO_ORIENTATION]: {
    horizontal: "Horizontal",
    vertical: "Vertical",
    inverted: "Inverted",
  },
  [CAR_SETUP_CHANGE_TYPES.SERVO_SPEED]: {
    "0.06": "0.06s/60°",
    "0.08": "0.08s/60°",
    "0.10": "0.10s/60°",
    "0.12": "0.12s/60°",
    "0.14": "0.14s/60°",
    "0.16": "0.16s/60°",
    "0.18": "0.18s/60°",
    "0.20": "0.20s/60°",
  },
  [CAR_SETUP_CHANGE_TYPES.SERVO_TORQUE]: {
    "8": "8kg·cm",
    "10": "10kg·cm",
    "12": "12kg·cm",
    "14": "14kg·cm",
    "16": "16kg·cm",
    "18": "18kg·cm",
    "20": "20kg·cm",
    "22": "22kg·cm",
    "24": "24kg·cm",
    "26": "26kg·cm",
    "28": "28kg·cm",
    "30": "30kg·cm",
  },
  [CAR_SETUP_CHANGE_TYPES.SERVO_HORN_LENGTH]: {
    "15": "15mm",
    "16": "16mm",
    "17": "17mm",
    "18": "18mm",
    "19": "19mm",
    "20": "20mm",
    "21": "21mm",
    "22": "22mm",
    "23": "23mm",
    "24": "24mm",
    "25": "25mm",
  },
  [CAR_SETUP_CHANGE_TYPES.BUMP_STEER_SETTING]: {
    none: "None",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  [CAR_SETUP_CHANGE_TYPES.STEERING_RATE]: {
    "50": "50%",
    "60": "60%",
    "70": "70%",
    "80": "80%",
    "90": "90%",
    "100": "100%",
    "110": "110%",
    "120": "120%",
    "130": "130%",
  },
  [CAR_SETUP_CHANGE_TYPES.MOTOR_POSITION]: {
    low: "Low",
    mid: "Mid",
    high: "High",
    rearward: "Rearward",
    forward: "Forward",
  },
  [CAR_SETUP_CHANGE_TYPES.SPUR_GEAR]: {
    "80": "80T",
    "82": "82T",
    "84": "84T",
    "86": "86T",
    "88": "88T",
    "90": "90T",
    "92": "92T",
    "94": "94T",
    "96": "96T",
    "98": "98T",
    "100": "100T",
  },
  [CAR_SETUP_CHANGE_TYPES.PINION_GEAR]: {
    "18": "18T",
    "19": "19T",
    "20": "20T",
    "21": "21T",
    "22": "22T",
    "23": "23T",
    "24": "24T",
    "25": "25T",
    "26": "26T",
    "27": "27T",
    "28": "28T",
  },
  [CAR_SETUP_CHANGE_TYPES.FDR]: {
    "3.5": "3.5",
    "4.0": "4.0",
    "4.5": "4.5",
    "5.0": "5.0",
    "5.5": "5.5",
    "6.0": "6.0",
    "6.5": "6.5",
    "7.0": "7.0",
    "7.5": "7.5",
    "8.0": "8.0",
  },
  [CAR_SETUP_CHANGE_TYPES.BELT_TENSION]: {
    loose: "Loose",
    medium: "Medium",
    tight: "Tight",
  },
  [CAR_SETUP_CHANGE_TYPES.FRONT_WHEEL_OFFSET]: {
    "3": "+3mm",
    "5": "+5mm",
    "7": "+7mm",
    "10": "+10mm",
  },
  [CAR_SETUP_CHANGE_TYPES.REAR_WHEEL_OFFSET]: {
    "3": "+3mm",
    "5": "+5mm",
    "7": "+7mm",
    "10": "+10mm",
  },
  [CAR_SETUP_CHANGE_TYPES.ESC_BOOST]: {
    "0": "0°",
    "5": "5°",
    "10": "10°",
    "15": "15°",
    "20": "20°",
    "25": "25°",
    "30": "30°",
  },
  [CAR_SETUP_CHANGE_TYPES.ESC_TURBO]: {
    "0": "0°",
    "5": "5°",
    "10": "10°",
    "15": "15°",
    "20": "20°",
    "25": "25°",
    "30": "30°",
  },
  [CAR_SETUP_CHANGE_TYPES.BATTERY_TYPE]: {
    shorty: "Shorty",
    fullSize: "Full Size",
    lcg: "LCG (Low Center of Gravity)",
  },
} as const;

export { CAR_SETUP_CHANGE_VALUES };

export const getCarSetupValues = (type: CarSetupChangeTypes) => {
  return (
    CAR_SETUP_CHANGE_VALUES[type as keyof typeof CAR_SETUP_CHANGE_VALUES] || {}
  );
};

export const getCarSetupLabel = (type: CarSetupChangeTypes, value: string) => {
  const values = getCarSetupValues(type);
  return (values as any)[value] || value;
};
